services:
  nginx:
    build:
      context: ./infra/nginx
    ports:
      - "80:80"
    volumes:
      - ./infra/nginx/default.prod.conf:/etc/nginx/conf.d/default.conf
      - ./darwin-real-estate-system:/var/www/html
    depends_on:
      - php

  php:
    build:
      context: ./infra/php
    expose:
      - "9000"
    ports:
      - "8081:9000"
    volumes:
      - ./darwin-real-estate-system:/var/www/html
    depends_on:
      - mysql

  mysql:
    build:
      context: ./infra/mysql
    platform: linux/x86_64
    ports:
      - "3306:3306"
    environment:
      - "LANG=C.UTF-8"
      - "MYSQL_ROOT_PASSWORD=password"
      - "MYSQL_DATABASE=real_estate_system"
    volumes:
      - type: volume
        source: mysql-volume
        target: /var/lib/mysql

  phpmyadmin:
    build:
      context: ./infra/phpmyadmin
    ports:
      - 8090:80
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: password
    depends_on:
      - mysql
      - php

networks:
  default:
    driver: bridge

volumes:
  mysql-volume:
    driver: local
